//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportProf.Resources.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been accepted successfully..
        /// </summary>
        public static string AcceptSuccess {
            get {
                return ResourceManager.GetString("AcceptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition has not been created..
        /// </summary>
        public static string CompCreateFailed {
            get {
                return ResourceManager.GetString("CompCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition has been created successfully..
        /// </summary>
        public static string CompCreateSuccess {
            get {
                return ResourceManager.GetString("CompCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition has not been deleted..
        /// </summary>
        public static string CompDelFailed {
            get {
                return ResourceManager.GetString("CompDelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your competition has been deleted successfully..
        /// </summary>
        public static string CompDelSuccess {
            get {
                return ResourceManager.GetString("CompDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition is ended..
        /// </summary>
        public static string CompEnded {
            get {
                return ResourceManager.GetString("CompEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition is started..
        /// </summary>
        public static string CompStart {
            get {
                return ResourceManager.GetString("CompStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been declined successfully..
        /// </summary>
        public static string DeclineSuccess {
            get {
                return ResourceManager.GetString("DeclineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is ended.
        /// </summary>
        public static string isEnd {
            get {
                return ResourceManager.GetString("isEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location has been added successfully..
        /// </summary>
        public static string LocAddSuccess {
            get {
                return ResourceManager.GetString("LocAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location has been deleted successfully..
        /// </summary>
        public static string LocDelSuccess {
            get {
                return ResourceManager.GetString("LocDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare for battle in competition.
        /// </summary>
        public static string PrepareComp {
            get {
                return ResourceManager.GetString("PrepareComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location is.
        /// </summary>
        public static string PrepareLoc {
            get {
                return ResourceManager.GetString("PrepareLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preapare for battle..
        /// </summary>
        public static string PrepareMain {
            get {
                return ResourceManager.GetString("PrepareMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been removed successfully..
        /// </summary>
        public static string RequestDelSuccess {
            get {
                return ResourceManager.GetString("RequestDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has not been sent..
        /// </summary>
        public static string RequestFailed {
            get {
                return ResourceManager.GetString("RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been sent successfully..
        /// </summary>
        public static string RequestSuccess {
            get {
                return ResourceManager.GetString("RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information has been saved successfully..
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your competition status is ended.
        /// </summary>
        public static string StatusEnded {
            get {
                return ResourceManager.GetString("StatusEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your competition status is prepared.
        /// </summary>
        public static string StatusPrepared {
            get {
                return ResourceManager.GetString("StatusPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your competition status is started.
        /// </summary>
        public static string StatusStarted {
            get {
                return ResourceManager.GetString("StatusStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations will not be able to accommodate the selected number of people..
        /// </summary>
        public static string UserCountError {
            get {
                return ResourceManager.GetString("UserCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your result is.
        /// </summary>
        public static string YourRes {
            get {
                return ResourceManager.GetString("YourRes", resourceCulture);
            }
        }
    }
}
